# encoding: utf-8
import datetime
from south.db import db
from south.v2 import SchemaMigration
from django.db import models

class Migration(SchemaMigration):

    def forwards(self, orm):
        db.execute("""CREATE VIEW fault_section_view AS
            SELECT s.id, s.sec_name, s.strike, s.episodi_is, s.episodi_ac,
            s.u_sm_d_min, s.u_sm_d_max, s.u_sm_d_pre, s.u_sm_d_com,
            s.low_d_min, s.low_d_max, s.low_d_pref, s.low_d_com, s.dip_min,
            s.dip_max, s.dip_pref, s.dip_com, s.dip_dir, s.down_thro,
            s.slip_typ, s.slip_com, s.slip_r_min, s.slip_r_max, s.slip_r_pre,
            s.slip_r_com, s.aseis_slip, s.aseis_com, s.dis_min, s.dis_max,
            s.dis_pref, s.re_int_min, s.re_int_max, s.re_int_pre, s.mov_min,
            s.mov_max, s.mov_pref, s.all_com, s.compiler, s.contrib, s.created,
            s.length_min, s.length_max, s.length_pre, t.geom FROM
            observations_faultsection
            s, observations_trace t WHERE (s.id = t.id)""")

        db.execute("""CREATE view fault_view AS SELECT s.id, s.fault_name,
        s.strike, s.episodi_is, s.episodi_ac, s.u_sm_d_min, s.u_sm_d_max,
        s.u_sm_d_pre, s.u_sm_d_com, s.low_d_min, s.low_d_max, s.low_d_pref,
        s.low_d_com, s.dip_min, s.dip_max, s.dip_pref, s.dip_com, s.dip_dir,
        s.down_thro, s.slip_typ, s.slip_com, s.slip_r_min, s.slip_r_max,
        s.slip_r_pre, s.slip_r_com, s.aseis_slip, s.aseis_com, s.dis_min,
        s.dis_max, s.dis_pref, s.re_int_min, s.re_int_max, s.re_int_pre,
        s.mov_min, s.mov_max, s.mov_pref, s.all_com, s.compiler, s.contrib,
        s.created, s.length_min, s.length_max, s.length_pre, t.geom FROM
        observations_fault s, observations_trace t WHERE s.id = t.id""")


    def backwards(self, orm):
        db.execute("DROP VIEW fault_section_view")
        db.execute("DROP VIEW fault_view")


    models = {
        'observations.fault': {
            'Meta': {'object_name': 'Fault'},
            'all_com': ('django.db.models.fields.IntegerField', [], {}),
            'aseis_com': ('django.db.models.fields.IntegerField', [], {}),
            'aseis_slip': ('django.db.models.fields.FloatField', [], {}),
            'compiler': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'contrib': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'created': ('django.db.models.fields.DecimalField', [], {'max_digits': '4', 'decimal_places': '3'}),
            'dip_com': ('django.db.models.fields.IntegerField', [], {}),
            'dip_dir': ('django.db.models.fields.IntegerField', [], {}),
            'dip_max': ('django.db.models.fields.IntegerField', [], {}),
            'dip_min': ('django.db.models.fields.IntegerField', [], {}),
            'dip_pref': ('django.db.models.fields.IntegerField', [], {}),
            'dis_max': ('django.db.models.fields.FloatField', [], {}),
            'dis_min': ('django.db.models.fields.FloatField', [], {}),
            'dis_pref': ('django.db.models.fields.FloatField', [], {}),
            'down_thro': ('django.db.models.fields.IntegerField', [], {}),
            'episodi_ac': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'episodi_is': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'fault_name': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'length_max': ('django.db.models.fields.FloatField', [], {}),
            'length_min': ('django.db.models.fields.FloatField', [], {}),
            'length_pre': ('django.db.models.fields.FloatField', [], {}),
            'low_d_com': ('django.db.models.fields.FloatField', [], {}),
            'low_d_max': ('django.db.models.fields.FloatField', [], {}),
            'low_d_min': ('django.db.models.fields.FloatField', [], {}),
            'low_d_pref': ('django.db.models.fields.FloatField', [], {}),
            'mov_max': ('django.db.models.fields.IntegerField', [], {}),
            'mov_min': ('django.db.models.fields.IntegerField', [], {}),
            'mov_pref': ('django.db.models.fields.IntegerField', [], {}),
            're_int_max': ('django.db.models.fields.IntegerField', [], {}),
            're_int_min': ('django.db.models.fields.IntegerField', [], {}),
            're_int_pre': ('django.db.models.fields.IntegerField', [], {}),
            'slip_com': ('django.db.models.fields.IntegerField', [], {}),
            'slip_r_com': ('django.db.models.fields.IntegerField', [], {}),
            'slip_r_max': ('django.db.models.fields.IntegerField', [], {}),
            'slip_r_min': ('django.db.models.fields.IntegerField', [], {}),
            'slip_r_pre': ('django.db.models.fields.IntegerField', [], {}),
            'slip_typ': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'strike': ('django.db.models.fields.IntegerField', [], {}),
            'u_sm_d_com': ('django.db.models.fields.FloatField', [], {}),
            'u_sm_d_max': ('django.db.models.fields.FloatField', [], {}),
            'u_sm_d_min': ('django.db.models.fields.FloatField', [], {}),
            'u_sm_d_pre': ('django.db.models.fields.FloatField', [], {})
        },
        'observations.faultsection': {
            'Meta': {'object_name': 'FaultSection'},
            'all_com': ('django.db.models.fields.IntegerField', [], {}),
            'aseis_com': ('django.db.models.fields.IntegerField', [], {}),
            'aseis_slip': ('django.db.models.fields.FloatField', [], {}),
            'compiler': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'contrib': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'created': ('django.db.models.fields.DecimalField', [], {'max_digits': '4', 'decimal_places': '3'}),
            'dip_com': ('django.db.models.fields.IntegerField', [], {}),
            'dip_dir': ('django.db.models.fields.IntegerField', [], {}),
            'dip_max': ('django.db.models.fields.IntegerField', [], {}),
            'dip_min': ('django.db.models.fields.IntegerField', [], {}),
            'dip_pref': ('django.db.models.fields.IntegerField', [], {}),
            'dis_max': ('django.db.models.fields.FloatField', [], {}),
            'dis_min': ('django.db.models.fields.FloatField', [], {}),
            'dis_pref': ('django.db.models.fields.FloatField', [], {}),
            'down_thro': ('django.db.models.fields.IntegerField', [], {}),
            'episodi_ac': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'episodi_is': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'fault': ('django.db.models.fields.related.ManyToManyField', [], {'to': "orm['observations.Fault']", 'symmetrical': 'False'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'length_max': ('django.db.models.fields.FloatField', [], {}),
            'length_min': ('django.db.models.fields.FloatField', [], {}),
            'length_pre': ('django.db.models.fields.FloatField', [], {}),
            'low_d_com': ('django.db.models.fields.FloatField', [], {}),
            'low_d_max': ('django.db.models.fields.FloatField', [], {}),
            'low_d_min': ('django.db.models.fields.FloatField', [], {}),
            'low_d_pref': ('django.db.models.fields.FloatField', [], {}),
            'mov_max': ('django.db.models.fields.IntegerField', [], {}),
            'mov_min': ('django.db.models.fields.IntegerField', [], {}),
            'mov_pref': ('django.db.models.fields.IntegerField', [], {}),
            're_int_max': ('django.db.models.fields.IntegerField', [], {}),
            're_int_min': ('django.db.models.fields.IntegerField', [], {}),
            're_int_pre': ('django.db.models.fields.IntegerField', [], {}),
            'sec_name': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'slip_com': ('django.db.models.fields.IntegerField', [], {}),
            'slip_r_com': ('django.db.models.fields.IntegerField', [], {}),
            'slip_r_max': ('django.db.models.fields.IntegerField', [], {}),
            'slip_r_min': ('django.db.models.fields.IntegerField', [], {}),
            'slip_r_pre': ('django.db.models.fields.IntegerField', [], {}),
            'slip_typ': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'strike': ('django.db.models.fields.IntegerField', [], {}),
            'u_sm_d_com': ('django.db.models.fields.FloatField', [], {}),
            'u_sm_d_max': ('django.db.models.fields.FloatField', [], {}),
            'u_sm_d_min': ('django.db.models.fields.FloatField', [], {}),
            'u_sm_d_pre': ('django.db.models.fields.FloatField', [], {})
        },
        'observations.faultsource': {
            'Meta': {'object_name': 'FaultSource'},
            'all_com': ('django.db.models.fields.IntegerField', [], {}),
            'area': ('django.db.models.fields.FloatField', [], {}),
            'aseis_com': ('django.db.models.fields.IntegerField', [], {}),
            'aseis_slip': ('django.db.models.fields.FloatField', [], {}),
            'compiler': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'contrib': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'created': ('django.db.models.fields.DecimalField', [], {'max_digits': '4', 'decimal_places': '3'}),
            'dip_com': ('django.db.models.fields.IntegerField', [], {}),
            'dip_dir': ('django.db.models.fields.IntegerField', [], {}),
            'dip_max': ('django.db.models.fields.IntegerField', [], {}),
            'dip_min': ('django.db.models.fields.IntegerField', [], {}),
            'dip_pref': ('django.db.models.fields.IntegerField', [], {}),
            'dis_max': ('django.db.models.fields.FloatField', [], {}),
            'dis_min': ('django.db.models.fields.FloatField', [], {}),
            'dis_pref': ('django.db.models.fields.FloatField', [], {}),
            'geom': ('django.contrib.gis.db.models.fields.PolygonField', [], {}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'length_max': ('django.db.models.fields.FloatField', [], {}),
            'length_min': ('django.db.models.fields.FloatField', [], {}),
            'length_pre': ('django.db.models.fields.FloatField', [], {}),
            'low_d_com': ('django.db.models.fields.FloatField', [], {}),
            'low_d_max': ('django.db.models.fields.FloatField', [], {}),
            'low_d_min': ('django.db.models.fields.FloatField', [], {}),
            'low_d_pref': ('django.db.models.fields.FloatField', [], {}),
            'magnitude': ('django.db.models.fields.IntegerField', [], {}),
            'mov_max': ('django.db.models.fields.IntegerField', [], {}),
            'mov_min': ('django.db.models.fields.IntegerField', [], {}),
            'mov_pref': ('django.db.models.fields.IntegerField', [], {}),
            'rake_com': ('django.db.models.fields.IntegerField', [], {}),
            'rake_max': ('django.db.models.fields.IntegerField', [], {}),
            'rake_min': ('django.db.models.fields.IntegerField', [], {}),
            'rake_pref': ('django.db.models.fields.IntegerField', [], {}),
            're_int_max': ('django.db.models.fields.IntegerField', [], {}),
            're_int_min': ('django.db.models.fields.IntegerField', [], {}),
            're_int_pre': ('django.db.models.fields.IntegerField', [], {}),
            'slip_com': ('django.db.models.fields.IntegerField', [], {}),
            'slip_r_com': ('django.db.models.fields.IntegerField', [], {}),
            'slip_r_max': ('django.db.models.fields.IntegerField', [], {}),
            'slip_r_min': ('django.db.models.fields.IntegerField', [], {}),
            'slip_r_pre': ('django.db.models.fields.IntegerField', [], {}),
            'slip_typ': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'source_nm': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'u_sm_d_com': ('django.db.models.fields.FloatField', [], {}),
            'u_sm_d_max': ('django.db.models.fields.FloatField', [], {}),
            'u_sm_d_min': ('django.db.models.fields.FloatField', [], {}),
            'u_sm_d_pre': ('django.db.models.fields.FloatField', [], {}),
            'width': ('django.db.models.fields.FloatField', [], {})
        },
        'observations.faultsourcetrace': {
            'Meta': {'object_name': 'FaultSourceTrace'},
            'geom': ('django.contrib.gis.db.models.fields.MultiLineStringField', [], {}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'})
        },
        'observations.faultsummary': {
            'Meta': {'object_name': 'FaultSummary'},
            'fid': ('django.db.models.fields.IntegerField', [], {}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.IntegerField', [], {'default': "'-1'", 'max_length': '100', 'blank': 'True'})
        },
        'observations.observations': {
            'Meta': {'object_name': 'Observations'},
            'dip_slip_rate_max': ('django.db.models.fields.CharField', [], {'max_length': '100', 'blank': 'True'}),
            'dip_slip_rate_min': ('django.db.models.fields.CharField', [], {'max_length': '100', 'blank': 'True'}),
            'dip_slip_rate_pref': ('django.db.models.fields.CharField', [], {'max_length': '100', 'blank': 'True'}),
            'hv_ratio': ('django.db.models.fields.CharField', [], {'max_length': '100', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'marker_age': ('django.db.models.fields.CharField', [], {'max_length': '100', 'blank': 'True'}),
            'net_slip_rate_max': ('django.db.models.fields.CharField', [], {'max_length': '100', 'blank': 'True'}),
            'net_slip_rate_min': ('django.db.models.fields.CharField', [], {'max_length': '100', 'blank': 'True'}),
            'net_slip_rate_pref': ('django.db.models.fields.CharField', [], {'max_length': '100', 'blank': 'True'}),
            'notes': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'observationType': ('django.db.models.fields.CharField', [], {'max_length': '1', 'blank': 'True'}),
            'rake': ('django.db.models.fields.CharField', [], {'max_length': '100', 'blank': 'True'}),
            'site': ('django.db.models.fields.CharField', [], {'max_length': '100', 'blank': 'True'}),
            'slipType': ('django.db.models.fields.CharField', [], {'max_length': '1', 'blank': 'True'}),
            'slip_rate_category': ('django.db.models.fields.CharField', [], {'max_length': '10', 'blank': 'True'}),
            'strike_slip_rate_max': ('django.db.models.fields.CharField', [], {'max_length': '100', 'blank': 'True'}),
            'strike_slip_rate_min': ('django.db.models.fields.CharField', [], {'max_length': '100', 'blank': 'True'}),
            'strike_slip_rate_pref': ('django.db.models.fields.CharField', [], {'max_length': '100', 'blank': 'True'}),
            'summary_id': ('django.db.models.fields.CharField', [], {'max_length': '100', 'blank': 'True'}),
            'vertical_slip_rate_max': ('django.db.models.fields.CharField', [], {'max_length': '100', 'blank': 'True'}),
            'vertical_slip_rate_min': ('django.db.models.fields.CharField', [], {'max_length': '100', 'blank': 'True'}),
            'vertical_slip_rate_pref': ('django.db.models.fields.CharField', [], {'max_length': '100', 'blank': 'True'})
        },
        'observations.siteobservation': {
            'Meta': {'object_name': 'SiteObservation'},
            'accuracy': ('django.db.models.fields.BigIntegerField', [], {}),
            'fault_section': ('django.db.models.fields.related.ManyToManyField', [], {'to': "orm['observations.FaultSection']", 'symmetrical': 'False'}),
            'geom': ('django.contrib.gis.db.models.fields.MultiLineStringField', [], {}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'notes': ('django.db.models.fields.TextField', [], {}),
            's_feature': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'scale': ('django.db.models.fields.BigIntegerField', [], {})
        },
        'observations.trace': {
            'Meta': {'object_name': 'Trace'},
            'accuracy': ('django.db.models.fields.BigIntegerField', [], {}),
            'fault_section': ('django.db.models.fields.related.ManyToManyField', [], {'to': "orm['observations.FaultSection']", 'symmetrical': 'False'}),
            'geom': ('django.contrib.gis.db.models.fields.MultiLineStringField', [], {}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'loc_meth': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'notes': ('django.db.models.fields.TextField', [], {}),
            'scale': ('django.db.models.fields.BigIntegerField', [], {}),
            'tid': ('django.db.models.fields.IntegerField', [], {})
        }
    }

    complete_apps = ['observations']
